<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Utang Statement — {{ $store->name }}</title>
    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
            font-size: 12px;
            color: #111;
            margin: 0;
            padding: 24px;
        }
        .header {
            border-bottom: 2px solid #1e5a9a;
            padding-bottom: 12px;
            margin-bottom: 18px;
        }
        .brand {
            font-size: 20px;
            font-weight: bold;
            color: #1e5a9a;
            margin: 0 0 4px;
        }
        .store {
            font-size: 14px;
            font-weight: bold;
            margin: 0;
        }
        .meta {
            color: #555;
            margin-top: 6px;
        }
        .summary {
            background: #f3f6fa;
            border: 1px solid #d7e0ea;
            border-radius: 6px;
            padding: 12px 14px;
            margin-bottom: 18px;
        }
        .summary-label {
            color: #555;
            font-size: 11px;
            text-transform: uppercase;
            letter-spacing: 0.04em;
        }
        .summary-value {
            font-size: 22px;
            font-weight: bold;
            margin-top: 2px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
        }
        th {
            text-align: left;
            background: #eef3f8;
            border-bottom: 1px solid #c9d5e2;
            padding: 8px;
            font-size: 11px;
            text-transform: uppercase;
            letter-spacing: 0.03em;
            color: #445;
        }
        td {
            border-bottom: 1px solid #e6ebf0;
            padding: 9px 8px;
            vertical-align: top;
        }
        .amount {
            text-align: right;
            font-weight: bold;
            white-space: nowrap;
        }
        .empty {
            text-align: center;
            color: #777;
            padding: 28px 8px;
        }
        .footer {
            margin-top: 22px;
            padding-top: 10px;
            border-top: 1px solid #dde3ea;
            color: #666;
            font-size: 10px;
        }
        .note {
            margin-top: 14px;
            color: #444;
            font-size: 11px;
            line-height: 1.45;
        }
    </style>
</head>
<body>
    <div class="header">
        <p class="brand">TindaWatch</p>
        <p class="store">{{ $store->name }}</p>
        <div class="meta">
            Utang / Open balances
            @if ($store->address)
                · {{ $store->address }}
            @endif
            <br>
            As of {{ $generatedAt }}
        </div>
    </div>

    <div class="summary">
        <div class="summary-label">Total open utang</div>
        <div class="summary-value">{{ $totalFormatted }}</div>
    </div>

    <table>
        <thead>
            <tr>
                <th style="width: 8%">#</th>
                <th>Customer</th>
                <th>Contact</th>
                <th class="amount">Balance</th>
            </tr>
        </thead>
        <tbody>
            @forelse ($customers as $index => $customer)
                <tr>
                    <td>{{ $index + 1 }}</td>
                    <td>{{ $customer['name'] }}</td>
                    <td>{{ $customer['contact'] ?: '—' }}</td>
                    <td class="amount">{{ $customer['balance_formatted'] }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="4" class="empty">No open utang.</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <p class="note">
        This statement lists customers with outstanding credit (utang) at
        {{ $store->name }}. Please settle with the store owner. Thank you.
    </p>

    <div class="footer">
        Generated by TindaWatch · {{ $generatedAt }}
    </div>
</body>
</html>
