<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Utang — {{ $customer->name }}</title>
    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
            font-size: 13px;
            color: #111;
            margin: 0;
            padding: 28px;
        }
        .header {
            border-bottom: 2px solid #1e5a9a;
            padding-bottom: 14px;
            margin-bottom: 22px;
        }
        .brand {
            font-size: 18px;
            font-weight: bold;
            color: #1e5a9a;
            margin: 0 0 4px;
        }
        .store {
            font-size: 15px;
            font-weight: bold;
            margin: 0;
        }
        .meta {
            color: #555;
            margin-top: 6px;
            font-size: 12px;
        }
        .card {
            border: 1px solid #d7e0ea;
            border-radius: 8px;
            padding: 18px;
            margin-bottom: 18px;
            background: #f8fafc;
        }
        .label {
            color: #555;
            font-size: 11px;
            text-transform: uppercase;
            letter-spacing: 0.04em;
        }
        .name {
            font-size: 20px;
            font-weight: bold;
            margin: 4px 0 10px;
        }
        .balance-label {
            color: #555;
            font-size: 12px;
        }
        .balance {
            font-size: 28px;
            font-weight: bold;
            color: #b45309;
            margin-top: 2px;
        }
        .note {
            line-height: 1.5;
            color: #333;
        }
        .footer {
            margin-top: 28px;
            padding-top: 10px;
            border-top: 1px solid #dde3ea;
            color: #666;
            font-size: 10px;
        }
    </style>
</head>
<body>
    <div class="header">
        <p class="brand">TindaWatch</p>
        <p class="store">{{ $store->name }}</p>
        <div class="meta">
            Utang reminder
            @if ($store->address)
                · {{ $store->address }}
            @endif
            <br>
            As of {{ $generatedAt }}
        </div>
    </div>

    <div class="card">
        <div class="label">Customer</div>
        <div class="name">{{ $customer->name }}</div>
        @if ($customer->contact)
            <div class="meta" style="margin-bottom: 14px;">{{ $customer->contact }}</div>
        @endif
        <div class="balance-label">Outstanding utang</div>
        <div class="balance">{{ $balanceFormatted }}</div>
    </div>

    <p class="note">
        Hi {{ $customer->name }}, you currently have an outstanding utang of
        <strong>{{ $balanceFormatted }}</strong> at {{ $store->name }}.
        Please settle with the store owner when you can. Salamat!
    </p>

    <div class="footer">
        Generated by TindaWatch · {{ $generatedAt }}
    </div>
</body>
</html>
